# 全局配置:
spring:
  profiles:
    active: dev
server:
  port: 8431
---
# 开发环境配置 dev

console-available: true
spring:
  profiles: dev
  output:
     ansi:
       enabled: always
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: 'jdbc:mysql://localhost/jmev?useUnicode=true&amp;characterEncoding=utf8&amp;characterSetResults=utf8&amp;zeroDateTimeBehavior=convertToNull'
    username: 'root'
    password: '123456'
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: '1' # 初始化大小
    minIdle: '1'
    maxActive: '5'
    maxWait: '60000' # 配置获取连接等待超时的时间
    timeBetweenEvictionRunsMillis: '60000' # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    minEvictableIdleTimeMillis: '300000'   # 配置一个连接在池中最小生存的时间，单位是毫秒
    validationQuery: 'SELECT 1 FROM DUAL'
    testWhileIdle: 'true'
    testOnBorrow: 'false'
    testOnReturn: 'false'
    poolPreparedStatements: 'false' # 打开PSCache，并且指定每个连接上PSCache的大小
    maxPoolPreparedStatementPerConnectionSize: '20'
    connectionProperties: 'druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000'
  redis:
    cluster:
      nodes:
        - 192.168.88.75:7000
        - 192.168.88.75:7001
        - 192.168.88.75:7002
        - 192.168.88.75:7003
        - 192.168.88.75:7004
        - 192.168.88.75:7005
#      host: localhost
#      port: 6379
#
---
# 生产环境配置 prod
spring:
  profiles: prod
  output:
     ansi:
       enabled: ALWAYS
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: 'jdbc:mysql://localhost/jmev?useUnicode=true&amp;characterEncoding=utf8&amp;characterSetResults=utf8&amp;zeroDateTimeBehavior=convertToNull'
      username: 'root'
      password: '123456'
      type: com.alibaba.druid.pool.DruidDataSource
      initialSize: '1' # 初始化大小
      minIdle: '1'
      maxActive: '5'
      maxWait: '60000' # 配置获取连接等待超时的时间
      timeBetweenEvictionRunsMillis: '60000' # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      minEvictableIdleTimeMillis: '300000'   # 配置一个连接在池中最小生存的时间，单位是毫秒
      validationQuery: 'SELECT 1 FROM DUAL'
      testWhileIdle: 'true'
      testOnBorrow: 'false'
      testOnReturn: 'false'
      poolPreparedStatements: 'false' # 打开PSCache，并且指定每个连接上PSCache的大小
      maxPoolPreparedStatementPerConnectionSize: '20'
      connectionProperties: 'druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000'

  redis:
    cluster:
      nodes:
        - 192.168.88.75:7000
        - 192.168.88.75:7001
        - 192.168.88.75:7002
        - 192.168.88.75:7003
        - 192.168.88.75:7004
        - 192.168.88.75:7005

